### ISSUE TITLE
Memory management and allocation

### ISSUE THREAD

**Issue by M4xi1m3** [numworks/epsilon-sample-app-cpp#1]
It seems like memory allocation is not in the sdk. Could it be possible to have a [sbrk](https://linux.die.net/man/2/sbrk) syscall and a simple allocator in the example source code ?

**Comment by RedGl0w** [comment]
> Thanks for the suggestion! The function `void eadk_heap_range(u32 * start_address, u32 * end_address)` will write the start and the end of an available heap in the addresses pointed by `start_address` and `end_address`.

Shouldn't it be better to have as parameter `void **` than a pointer to a numeric variable?
