### ISSUE TITLE
Applications do not work on latest version (17.2.0)

### ISSUE THREAD

**Issue by AngeAdonys** [numworks/epsilon-sample-app-cpp#17]
I installed the template app using the command "dfu-util -i 0 -a 0 -s 0x90110000:leave -D application.bin" and it appears on the home screen, but when I open it, it just takes me to the country selection screen, and the apps disappear. On the beta, the calculator just restarts and the app does not appear.

**Comment by EmilieNumworks** [comment]
Short answer: rather use `make clean; make run`

A little explanation: 0x90110000 address is outdated. The external-apps flash range should be extracted dynamically from the userland header (using `eadk/get_device_information.py` for instance). This is explained in the README.
