### ISSUE TITLE
Is external data working?

### ISSUE THREAD

**Issue by Adi-df** [numworks/epsilon-sample-app-cpp#26]
As there's no complete example of how to use external data, I tried to just uncomment the line in main.cpp and displaying its content with `drawString`
```cpp
#include "display.h"
#include "eadk.h"
#include "palette.h"

extern "C" const char eadk_app_name[] = "Voord";
extern "C" const uint32_t eadk_app_api_level = 0;
extern "C" void _eadk_main();
/* If the app were to require an external data, the symbol 'eadk_external_data'
 * could be used without any definition in the .nwa. The .bin would require an
 * external .o defining eadk_external_data in order to bin the executable. */
extern "C" const unsigned char eadk_external_data[];

void _eadk_main() {
  EADK::Display::pushRectUniform(EADK::Display::Rect(0, 0, Display::Width, Display::Height), Black);
  EADK::Display::drawString(reinterpret_cast<const char*>(eadk_external_data), EADK::Display::Point(0,0), false, White, Black);
}
```
Then I compiled using the usual `make run`:
```
CXX     src/alien.cpp
CXX     src/eadk.cpp
CXX     src/life.cpp
CXX     src/main.cpp
CXX     src/rocket.cpp
CXX     src/spaceship.cpp
CXX     src/score.cpp
NWI     src/icon.png
INLINE  target/icon.nwi
LD      target/voord.nwa
INSTALL target/voord.nwa
Installing target/voord.nwa with {}
Got infos
/home/adriend/.nvm/versions/node/v16.1.0/bin/nwlink:linker.ld:7: undefined symbol `_binary_input_dat_start' referenced in expression
```
I ignored the error as `make run` don't provide external data. So I used nwlink to install the app with a test.data file as follows:
```
echo "Hello Cpp\0" > test.data
nwlink install-nwa -d test.data target/voord.nwa
```
And I have had the same error:
```
Installing target/voord.nwa with { externalData: 'test.data' }
Got infos
/home/adriend/.nvm/versions/node/v16.1.0/bin/nwlink:linker.ld:7: undefined symbol `_binary_input_dat_start' referenced in expression
```
So did I use external data the wrong way, or is it just not working?

**Comment by Adi-df** [comment]
Well after trying with the online installer it seems to work perfectly! So is it a problem with my toolchain or with the nwlink tool?

**Comment by Ecco** [comment]
The root problem is that this sample app doesn't use any external data, and so you're left on your own to figure out how to make it work. But the tools *do* work, they're just hard to figure out 😄 

Namely, if you want to link external data on your own computer, you should pass the `--external-data` flag to `nwlink install-nwa` or `nwlink link-nwa`. This is (poorly) documented in `nwlink help`.

I will close this issue because external data *is* working, but we should indeed provide some sample code using external data.
