### ISSUE TITLE
Build the app on Windows

### ISSUE THREAD

**Issue by Valmontechno** [numworks/epsilon-sample-app-cpp#28]
https://github.com/numworks/epsilon-sample-app-cpp/blob/1bccbd1459c39171956bf809296b4f73dfdd070e/README.md?plain=1#L35-L38
What is the equivalent command to build the application on Windows operating system?

**Comment by yannis300307** [comment]
Hello,
You need to install the brew package manager to run the first command.
You can install [brew.sh](https://brew.sh/) on WSL with the following command `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`. If you don't have curl installed on wsl, just install it with `sudo apt install curl`.

To install the ARM compiler run `sudo apt install gcc-arm-none-eabi binutils-arm-none-eabi`

Then, you can run the first command. For the second command, you have to install Make. To do so, just run `sudo apt install build-essential` in wsl. You can now run the both command. 

Note that currently, the lib used by numworks called `nwlink` crashes with the latest version of node. So, you have to downgrade the node version using NVM. 

Install NVM with `curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash`. 

Now, install the v20.16.0 version of node that seems to work with nwlink with `nvm install v20.16.0` and now, you should be able to run `make build`
