### ISSUE TITLE
Have static RAM for external app

### ISSUE THREAD

**Issue by RedGl0w** [numworks/epsilon-sample-app-cpp#5]
The stm32f730 doesn't have any sort of MMU, which drastically reduces the possibilities to have static c vars :
- either, the apps_container buffer could be at a specific address, and so the apps would be linked for this address
- or the ITCM RAM which isn't yet used at all by epsilon could be used (this is how zardam's external works)

**Comment by EmilieNumworks** [comment]
You can dynamically ask for the range of sRAM where the external apps can be linked as explained in README.
